// <auto-generated />
using GradeProject.ScoreServie.Infrastructure.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GradeProject.ScoreService.SqlServer.Migrations.Migrations
{
    [DbContext(typeof(ScoresContext))]
    [Migration("20180712054009_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GradeProject.ScoreService.Domain.ScoreInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("GameId");

                    b.Property<string>("GameName")
                        .IsRequired();

                    b.Property<DateTime>("LastUpdate");

                    b.Property<double>("Score");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("GradeProject.ScoreService.Domain.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("GradeProject.ScoreService.Domain.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("StatusId");

                    b.Property<double>("Total");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GradeProject.ScoreService.Domain.UserStatus", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("StatusId");

                    b.HasKey("UserId", "StatusId");

                    b.HasIndex("StatusId");

                    b.ToTable("UserStatus");
                });

            modelBuilder.Entity("GradeProject.ScoreService.Domain.ScoreInfo", b =>
                {
                    b.HasOne("GradeProject.ScoreService.Domain.User", "User")
                        .WithMany("ScoreInfo")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("GradeProject.ScoreService.Domain.UserStatus", b =>
                {
                    b.HasOne("GradeProject.ScoreService.Domain.Status", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GradeProject.ScoreService.Domain.User", "User")
                        .WithMany("Status")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
