// <auto-generated />
using System;
using GradeProject.ScoreService.Infrastrucutre.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GradeProject.ScoreService.PostgreSQL. Migrations.Migrations
{
    [DbContext(typeof(ScoresContext))]
    partial class ScoresContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", "'uuid-ossp', '', ''")
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GradeProject.ScoreService.Domain.ScoreInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("GameName")
                        .IsRequired();

                    b.Property<DateTime>("LastUpdate");

                    b.Property<double>("Score");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("GradeProject.ScoreService.Domain.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("GradeProject.ScoreService.Domain.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("StatusId");

                    b.Property<double>("Total");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GradeProject.ScoreService.Domain.UserStatus", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("StatusId");

                    b.HasKey("UserId", "StatusId");

                    b.HasIndex("StatusId");

                    b.ToTable("UserStatus");
                });

            modelBuilder.Entity("GradeProject.ScoreService.Domain.ScoreInfo", b =>
                {
                    b.HasOne("GradeProject.ScoreService.Domain.User", "User")
                        .WithMany("ScoreInfo")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("GradeProject.ScoreService.Domain.UserStatus", b =>
                {
                    b.HasOne("GradeProject.ScoreService.Domain.Status", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GradeProject.ScoreService.Domain.User", "User")
                        .WithMany("Status")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
